### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by funmolde** [Djmcflush/RaveFussion#2]
Hello 
What's the program for?
I've installed and run it but I don't understand. 
Thank you
![Screenshot 1](https://github.com/Djmcflush/RaveFussion/assets/13144261/ef316046-5dcb-4ede-a408-98eab44cb9f8)

**Comment by Djmcflush** [comment]
The idea was to continuously remix a song using the coordinates of your mouse. The UI was never fully finished but if you take a look st the backend you'll see two sequence to sequence models. The first being a diffusion model the second a Rave model which takes images -> music, the second music -> music. Happy hacking !

**Comment by funmolde** [comment]
Thank you -_-
